### ISSUE TITLE
emqtt_benchamark测试结果数据

### ISSUE THREAD

**Issue by huangbaoquan** [emqtt/emqtt_benchmark#11]
测试参数：emqtt_bench_pub  -c 20000 -q 2 -I 10，我模拟2万个客户端，发送消息质量为2，每个10ms发送消息，得带的测试结果数据是：sent(15520682)： total=19818018,rate=81616(msg/sec)，这些结果数据代表什么含义啊？是每一台客户端发送消息81616？还是2万台客户端速率？sent是指发送成功发送消息数量？total是总共发送消息数量？

**Comment by satrox28** [comment]
I am receiving this error once the client reaches 16k connections.

conneted: 16252
client 33748 EXIT: {shutdown,eaddrnotavail}
Topics: ["/t/b/a/%i"]

I have added the below config on sysctl.conf

net.ipv4.ip_local_port_range = 1024     65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 5242880      5242880 15242880
net.ipv4.tcp_tw_recycle = 1
fs.file-max = 20000000
fs.nr_open = 20000000

ulimit -a

**Comment by Gilbert-Wong** [comment]
English Please !.
