### ISSUE TITLE
Example of multiple topic

### ISSUE THREAD

**Issue by duc1609** [emqtt/emqtt_benchmark#12]
Hi, could you elaborate an example of how to use options in topic.
For example:
- 1000 clients publishes to 10 topics (100 clients to each topic)
- 100 clients, each client subscribes to 5 topics.

Thanks.

**Comment by vidhill** [comment]
``` bash
./emqtt_bench_sub -h localhost -p 8083 --count 1000 --topic alarms/cats --topic alarms/dogs --topic alarms/mice
```
