### ISSUE TITLE
Unable to benchmark on 1500 Subscription

### ISSUE THREAD

**Issue by DataEngg** [emqtt/emqtt_benchmark#15]
I have created a cluster of two nodes and join them together, each node is of 1 GB RAM nd 24 GB HardDisk. As well as I have HAproxy behind the two cluster for load balancing the request to EMQTTD cluster. I have tunned  each of the machines according to the tunning guide. I have defined all the tunning in the file /etc/sysctl.conf. 

**/etc/sysctl.conf**
fs.file-max = 1048576
net.ipv4.tcp_max_tw_buckets=1048576
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
net.netfilter.nf_conntrack_max=1000000
net.nf_conntrack_max=1000000
net.core.somaxconn=32768
net.ipv4.tcp_max_syn_backlog=16384
net.core.netdev_max_backlog=16384
net.ipv4.ip_local_port_range=1000 65535
net.core.rmem_default=262144
net.core.wmem_default=262144
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.optmem_max=16777216
net.ipv4.tcp_rmem=1024 4096 16777216
net.ipv4.tcp_wmem=1024 4096 16777216

when I hit the load balancer with emqttd_benchmark command

./emqtt_bench_sub -h *.*.*.* -p **** -c 1500 -i 100 -t ****** -q 2 -k 40000 -c false

then afterwards I get an error of [error] [Client <0.4506.0>] CONNACK Timeout! or  I get an error of 
client 2499 EXIT: {shutdown,tcp_closed}.

when I execute the benchmark command with 500 clients then it work well without giving any error but when I increase the clients then it throws an error of CONNACK Timeout! or client 2499 EXIT: {shutdown,tcp_closed}.

Please help me how should I do it. My target is to make at least 10000 concurrent connections with the cluster and able to send a message to all 10000 clients.

**Comment by emqplus** [comment]
Hi @DataEngg, you can check the statistics of TCP listeners:

```
./bin/emqttd_ctl listeners
```

And then check if there are error logs in logs/*, Thanks.

**Comment by DataEngg** [comment]
I have executed the command , it show the current_clients which increases up to sometime then afterwards it does not increase  and go on decreasing, it decreases when I see a error at client side and I get another error too like emfile and econnrefused.

**Comment by DataEngg** [comment]
@emqplus Bro emqttd_error.log  does not show any error

**Comment by DataEngg** [comment]
I got the error and now I am able to connect 64K concurrent clients. Error is of my problem of internet.
