### ISSUE TITLE
it can’t work  Follow the steps

### ISSUE THREAD

**Issue by zhiyoujingtian** [emqtt/emqtt_benchmark#18]
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/emqttc to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/getopt to be an app dir (containing ebin/*.app), but no .app found.
==> emqtt_benchmark-master (get-deps)
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/emqttc to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/getopt to be an app dir (containing ebin/*.app), but no .app found.
Pulling emqttc from {git,"git://github.com/emqtt/emqttc.git",
                         {branch,"master"}}
正克隆到 'emqttc'...
Pulling getopt from {git,"https://github.com/jcomellas/getopt.git",
                         {branch,"master"}}
正克隆到 'getopt'...
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/gen_logger to be an app dir (containing ebin/*.app), but no .app found.
==> getopt (get-deps)
==> emqttc (get-deps)
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/gen_logger to be an app dir (containing ebin/*.app), but no .app found.
Pulling gen_logger from {git,"https://github.com/emqtt/gen_logger.git",
                             {branch,"master"}}
正克隆到 'gen_logger'...
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
==> gen_logger (get-deps)
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
Pulling lager from {git,"git://github.com/basho/lager.git",{branch,"master"}}
正克隆到 'lager'...
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
==> lager (get-deps)
WARN:  Expected /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.8"}}
正克隆到 'goldrush'...
==> goldrush (get-deps)
==> goldrush (compile)
ERROR: OTP release R17 or later is required, you have: R16B03
ERROR: compile failed while processing /home/congzhou/engyne/test/Server/emqtt_benchmark-master/deps/goldrush: rebar_abort
make: *** [compile] 错误 1

**Comment by msdevanms** [comment]
You need to upgrade Erlang to OTP 17 or 17+
Please go to the following website for getting new versions.
https://www.erlang.org/downloads

**Comment by emqplus** [comment]
@zhiyoujingtian please upgrade Erlang/OTP to R17+.
