### ISSUE TITLE
How do you select locat IP when starting a client?

### ISSUE THREAD

**Issue by galvezlj** [emqtt/emqtt_benchmark#2]
My Client machine has multiple IP and I would like to make use of them when connecting to my emqttd broker. This should allow me to have more than 65K connections from one client machine given that my client machine has adequate RAM and CPU.

**Comment by erylee** [comment]
Support 'ifaddr' option now:

```
./emqtt_bench_pub --ifaddr 192.168.1.10
./emqtt_bench_sub --ifaddr 192.168.2.10
```
