### ISSUE TITLE
emqtt benchmark client error

### ISSUE THREAD

**Issue by satrox28** [emqtt/emqtt_benchmark#24]
Hi,

We are trying to evaluate the emqtt server with 1node - 4vcpu, 16gb ram, 500K connection limit.

I am receiving this error on the client once it reaches 16k connections.

conneted: 16252
client 33748 EXIT: {shutdown,eaddrnotavail}
Topics: ["/t/b/a/%i"]

I have added the below config on sysctl.conf

net.ipv4.ip_local_port_range = 1024     65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 5242880      5242880 15242880
net.ipv4.tcp_tw_recycle = 1
fs.file-max = 20000000
fs.nr_open = 20000000

ulimit -a

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62800
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 500000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 500000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

OS: Ubuntu 16.10

Can you help me to fix this issue, I feel its like something to do with kernel parameters.

**Comment by promission** [comment]
I encountered the same problem，Will you fix it?

**Comment by emqplus** [comment]
@promission There is a limit that one process can only use 32768 known ports on some VM.

**Comment by promission** [comment]
@emqplus   I tried 3k connections, there are still two failures， “client 1112 EXIT: {shutdown,eaddrnotavail}”
