### ISSUE TITLE
usr/bin/env: escript: No such file or directory

### ISSUE THREAD

**Issue by MuskaWu** [emqtt/emqtt_benchmark#25]
Environment

-Server: AWS

OS: Centos 7
Erlang/OTP: otp_src_19.2.tar.gz
EMQ: v2.0.4
Description

I have two Server on AWS :+1:

OS: Centos 7
EMQ: v2.0.4

sorry I want to make emqtt_benchmark
but...
[root@ip-xxx-xx-xx-xx emqtt_benchmark]# make
/usr/bin/env: escript: No such file or directory
make: *** [get-deps] Error 127

Do I have to have an env directory?
And then How I make escript??

**Comment by GLENNCHAN888** [comment]
Hi I also have the same problem, do you fix it?

**Comment by turtleDeng** [comment]
@GLENNCHAN888  Please install Erlang OTP

**Comment by emqplus** [comment]
@GLENNCHAN888 @MuskaWu Suggest to use the JMeter to benchmark EMQ: https://github.com/emqtt/mqtt-jmeter
