### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by hezhijun** [emqtt/emqtt_benchmark#26]
![qq 20170301151857](https://cloud.githubusercontent.com/assets/1496542/23449635/6bd9de8a-fe92-11e6-8f92-5a49fb8245bc.jpg)

**Comment by hezhijun** [comment]
I have erlang 19 installed
![qq 20170301152101](https://cloud.githubusercontent.com/assets/1496542/23449696/993e0856-fe92-11e6-91da-99786ce1bbc3.jpg)

**Comment by emqplus** [comment]
@hezhijun sorry for the late reply. You Erlang/OPT environment missed 'crypto' library. Please fix it first.
