### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by chenjinlin616** [emqtt/emqtt_benchmark#27]
WARN:  Expected /home/mqtt/emqtt_benchmark/deps/emqttc to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/mqtt/emqtt_benchmark/deps/getopt to be an app dir (containing ebin/*.app), but no .app found.
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,enoent}},
                                [{rebar_utils,otp_release1,1,
                                  [{file,"src/rebar_utils.erl"},{line,391}]},
                                 {rebar_utils,get_arch,0,
                                  [{file,"src/rebar_utils.erl"},{line,92}]},
                                 {rebar_port_compiler,default_env,0,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,574}]},
                                 {rebar_port_compiler,setup_env,2,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,181}]},
                                 {rebar_core,'-setup_envs/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,522}]},
                                 {lists,foldl,3,
                                  [{file,"lists.erl"},{line,1262}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,293}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,258}]}]}}
make: *** [get-deps] 错误

**Comment by Gilbert-Wong** [comment]
Do you install rebar on your system. It looks like rebar's problem.
