### ISSUE TITLE
Please add Subscribe to the Benchmark Tool

### ISSUE THREAD

**Issue by galvezlj** [emqtt/emqtt_benchmark#3]
Please add the capability to measure the number of maximum connections while each client is subscribing to their queues.

**Comment by erylee** [comment]
@galvezlj, I released the new benchmark tool with a emqtt_bench_sub command:

For example, 50K clients that each subscribes a topic 'test/%i':

```
./emqtt_bench_sub -h server -p 1883 -c 50000 -i 10 -t test/%i -q 1
```

Please check the README.md. Thanks.
