### ISSUE TITLE
authentication option -u <username> -P <passwor> does not work

### ISSUE THREAD

**Issue by zhongjin616** [emqtt/emqtt_benchmark#4]
when connect to emqttd with authentication like this:

`./emqtt_bench_sub -h 192.168.0.45 -p 1883 -u admin -P admin -c 4000 -i 30 -t bench/%i`

Clients are not allow to sub with Error: 'CONNACK_CREDENTIALS'. And the emqttd log says the username is 'undefined'.

But the other benchmark  (takanorig/mqtt-bench)[https://github.com/takanorig/mqtt-bench] does the right job.

**Comment by erylee** [comment]
./rebar update-deps && make
