### ISSUE TITLE
What is the variable `%i` meaning in topic

### ISSUE THREAD

**Issue by hillbun** [emqtt/emqtt_benchmark#40]
bench/%i

**Comment by Gilbert-Wong** [comment]
It means variable, please use English to open issue.

**Comment by hillbun** [comment]
for example:

./emqtt_bench_pub  -c 50000 -I 1 -t bench/%i -s 256

%i means from 1 to 50000?

**Comment by Gilbert-Wong** [comment]
No, the i is used to specify the connection interval and the corresponding topic. it means 1, not 1 to 50000

**Comment by hillbun** [comment]
How can I achieve if I need to publish to 50000 different topics?

**Comment by hillbun** [comment]
I am asking  -t bench/%i
not -I 1

**Comment by Gilbert-Wong** [comment]
I misunderstand what you say, %i is number, %u is username and %c is client_id. If you want to publish to 50000 topics, you can write a shell script to use loop to achieve it.

**Comment by hillbun** [comment]
does it mean?

bench/1
bench/2
bench/3
...
bench/50000

**Comment by Gilbert-Wong** [comment]
Yes.
