### ISSUE TITLE
emqtt_bench_pub or emqtt_bench_sub exception error

### ISSUE THREAD

**Issue by mopybird** [emqtt/emqtt_benchmark#44]
escript: exception error: undefined function getopt:parse/2
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 680)
  in call from erl_eval:expr/5 (erl_eval.erl, line 449)
  in call from escript:eval_exprs/5 (escript.erl, line 872)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1

**Comment by Gilbert-Wong** [comment]
Could you please tell me what's your scenario? And how did you encounter this problem?

**Comment by jt-tech** [comment]
I also have such a problem.

```
./emqtt_bench_sub --help
escript: exception error: undefined function getopt:parse/2
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 680)
  in call from erl_eval:expr/5 (erl_eval.erl, line 449)
  in call from escript:eval_exprs/5 (escript.erl, line 872)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
```

**Comment by BEWINDOWEB** [comment]
I have the same problem too too too ......
# Details
At first, I set a **ubuntu 16.04** virtual machine on vmware 12 with windows 10. And installed the erlang 18 by:
```
apt-get install erlang
```
which apt source.list is [Qinghua University Ubuntu 16.04](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/):
```
# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse

# 预发布软件源，不建议启用
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
```
Then installed rebar3 by :
```
apt-get install git
git clone https://github.com/erlang/rebar3.git  /tmp/rebar3.git
cd /tmp/rebar3.git
./bootstrap
./rebar3 local install
cp rebar3 /usr/local/bin
apt-get install vim
vi /etc/profile
      export PATH=$PATH:/usr/local/bin/rebar3
source /etc/profile
which rebar3
```
And make the emqtt-benchmark:
```
make
```
it shows:
```
===> Verifying dependencies...
===> Fetching emqttc ({git,"https://github.com/emqtt/emqttc.git",
                                 {ref,
                                     "9be166ff1c7deadb2763b5a27c1bba3c635fcee9"}})
===> Fetching getopt ({git,"https://github.com/jcomellas/getopt.git",
                                 {ref,
                                     "784b0ea8777f754fc96099b385d00d9cf5b137d8"}})
===> Compiling emqttc
_build/default/lib/emqttc/src/emqttc.erl:646: Warning: variable 'Name' is unused

===> Compiling getopt
===> Compiling emqtt_benchmark
```
And lib dir is generated:
```
|- _build
    |- default 
        |- lib
            |- emqtt_benchmark
            |- emqttc
            |- getopt
```
And then use the command it throws:
```
./emqtt_bench_pub --help
escript: exception error: undefined function getopt:parse/2
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 670)
  in call from erl_eval:expr/5 (erl_eval.erl, line 438)
  in call from escript:eval_exprs/5 (escript.erl, line 871)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 557)
  in call from escript:interpret/4 (escript.erl, line 787)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
```
# I've Tried
(1) emqtt_benchmark is a 2-years-ago project, so it cannot be the code problem.
(2) May be the newest emqttc and getopt releases are not compatible with benchmark, [the latest emqttc release](https://github.com/emqtt/emqttc/releases) is published at 2015, and [getopt](https://github.com/jcomellas/getopt/releases) is 2017, so i try to use getopt 0.8.2 which published at 2013:
```
make clean
rm -rf _build
vi rebar.lock
[{<<"emqttc">>,
  {git,"https://github.com/emqtt/emqttc.git",
       {ref,"9be166ff1c7deadb2763b5a27c1bba3c635fcee9"}},
  0},
 {<<"getopt">>,
  {git,"https://github.com/jcomellas/getopt.git",
       {ref,"388dc95caa7fb97ec7db8cfc39246a36aba61bd8"}},
  0}].
```
it doesn't work.
(3) i try to reinstall [erlang v19/v20](https://www.erlang-solutions.com/resources/download.html), reinstall [rebar3 v3.7.4 v3.7.0](https://github.com/erlang/rebar3/releases), it doesn't work.
(4) the problem file is:
```
find / -name "erl_eval.erl"
/usr/lib/erlang/lib/stdlib-3.0/src/erl_eval.erl
```
but may be it's not the root cause.

# 希望能修复这个bug，实在是找不到办法了，QwQ

**Comment by ddwla4** [comment]
# ./emqtt_bench_pub --help
escript: exception error: undefined function getopt:parse/2
  in function  erl_eval:do_apply/6 (erl_eval.erl, line 670)
  in call from erl_eval:expr/5 (erl_eval.erl, line 438)
  in call from escript:eval_exprs/5 (escript.erl, line 873)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 557)
  in call from escript:interpret/4 (escript.erl, line 789)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1

**Comment by tonywang** [comment]
@ddwla4 @BEWINDOWEB 
The tools could use for me, the follow step as below:
1. make sure your erl and rebar3 installed
2. execute "make" in the emqtt_benchmark and could received the success info, if not please check step 1
3. after DO "make" command, there is a "_build" dir has been created, but the script need deps dir, you can find this frome the emqtt_bench_sub/emqtt_bench_pub like below:
%%! -pa ./ebin -pa deps/emqttc/ebin -pa deps/getopt/ebin -pa deps/gen_logger/ebin -pa deps/goldrush/ebin -smp true +K true +A 16 +P 200000 -env ERL_MAX_PORTS 100000 -env ERTS_MAX_PORTS 100000

4. just need create the deps directory and copy/link these lib folders, such as below:
lrwxrwxrwx 1 tony tony   37 Jan 18 03:46 emqtt_benchmark -> ../_build/default/lib/emqtt_benchmark/
lrwxrwxrwx 1 tony tony   28 Jan 18 03:46 emqttc -> ../_build/default/lib/emqttc/
lrwxrwxrwx 1 tony tony   28 Jan 18 03:46 getopt -> ../_build/default/lib/getopt/

5. and then try tpye "./emqtt_bench_sub --help", it works.

**Comment by tonywang** [comment]
When execute ./emqtt_bench_sub --ipaddr localhost -t test, throw the erros as blow:
escript: exception error: undefined function emqtt_benchmark:main/2
  in function  erl_eval:local_func/6 (erl_eval.erl, line 557)
  in call from escript:interpret/4 (escript.erl, line 787)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1
  in call from init:start_em/1

I am not familiar with erlang structure, I just update the emqtt_bench_sub/emqtt_bench_pub as follow:

`%%! -pa ./ebin -pa deps/emqttc/ebin -pa deps/getopt/ebin -pa deps/gen_logger/ebin -pa deps/goldrush/ebin -smp true +K true +A 16 +P 200000 -env ERL_MAX_PORTS 100000 -env ERTS_MAX_PORTS 100000`

change to:

`%%! -pa ./ebin -pa deps/emqttc/ebin -pa deps/getopt/ebin -pa deps/gen_logger/ebin -pa deps/goldrush/ebin -pa deps/emqtt_benchmark/ebin -smp true +K true +A 16 +P 200000 -env ERL_MAX_PORTS 100000 -env ERTS_MAX_PORTS 100000`

**Comment by Gilbert-Wong** [comment]
Yes, this problem exactly exists, I have fixed it.

**Comment by chenhais** [comment]
> fixed

not fixed
