### ISSUE TITLE
After 1003 concurrent connections client 98959 EXIT: {shutdown,emfile} exceptions is coming

### ISSUE THREAD

**Issue by VIKRAMAS** [emqtt/emqtt_benchmark#46]
I am trying to connect to 100000 connections to emqttd. But after 1003 connections i am getting `client 98959 EXIT: {shutdown,emfile}` exception but as per configuration it has to handle 1M connections(I have done as per documentation). In jmeter, it is reaching 100000 connections. But if I am  trying using emqttd benchmark code it is reaching up to 1003 only.

`./emqtt_bench_pub -h 192.168.1.129 -p 1883 -c 100000 -i 100 -I 2000 -t bench/%i -s 256`

**Comment by HJianBo** [comment]
Hi, @VIKRAMAS Could you tune the file limit os params?  https://developer.emqx.io/docs/emq/v3/en/tune.html

**Comment by BEWINDOWEB** [comment]
I have the same problem. but when i check the open files num:
```
ulimit -a
open files ..........  1024
```
it's only 1024，so your 1003 may be limited by this number
and i set it higher：
```
ulimit -n 1000000
```
then it works fine.
