### ISSUE TITLE
client EXIT: {shutdown, tcp_closed}

### ISSUE THREAD

**Issue by oedemis** [emqtt/emqtt_benchmark#8]
If i start the benchmark with 50K subscribers i receive after around thousandth clients the output
client EXIT: {shutdown, tcp_closed}, What is the reason. 
My sysctl.conf
# For binary values, 0 is disabled, 1 is enabled. See sysctl(8) and
# sysctl.conf(5) for more details.
# Controls IP packet forwarding
net.ipv4.ip_forward = 0
# Controls source route verification
net.ipv4.conf.default.rp_filter = 1
# Do not accept source routing
net.ipv4.conf.default.accept_source_route = 0
# Controls the System Request debugging functionality of the kernel
kernel.sysrq = 0
# Controls whether core dumps will append the PID to the core filename.
# Useful for debugging multi-threaded applications.
kernel.core_uses_pid = 1
# Controls the use of TCP syncookies
net.ipv4.tcp_syncookies = 1
# Disable netfilter on bridges.
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
# Controls the default maxmimum size of a mesage queue
kernel.msgmnb = 65536
# Controls the maximum size of a message, in bytes
kernel.msgmax = 65536
# Controls the maximum shared segment size, in bytes
kernel.shmmax = 68719476736
# Controls the maximum number of shared memory segments, in pages
kernel.shmall = 4294967296
#ipv6 support in the kernel, set to 0 by default
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

net.ipv4.tcp_fin_timeout = 30
fs.file-max = 5097152
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.core.rmem_default = 524288
net.core.wmem_default = 524288
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.ip_local_port_range = 1024 65535

And here limits.conf
#<domain> <type> <item> <value>
......
* hard nofile 500000
* soft nofile 500000
root hard nofile 500000
root soft nofile 500000

**Comment by erylee** [comment]
Hi @oedemis, the kernel parameters are right. It seems emqtt_benchmark did not connect to the broker successfully. Please check logs/emqttd_error.log or run './bin/emqttd_ctl listerners'

**Comment by oedemis** [comment]
Hi, I'm testing the mosquitto mqtt broker

**Comment by erylee** [comment]
Please check mosquitto config and logs, 'tcp_closed' means the broker closed the TCP connection actively.

**Comment by vincentsmh** [comment]
I have the same problem and the emqtt broker show this message in log

07:23:53.003 <0.416.0> [error] Failed to start connection on 0.0.0.0:1883 - maxlimit
